common: &common
  sessions: create
  translations: show
  templates: crud
  users: [crud, current]
  welcome: read

signed_user: &signed_user

admin_spec: &admin_spec
  spec_model: [do_crazy_thing, do_common_thing, do_regular_thing, do_visitor_thing]

regular_spec: &regular_spec
  spec_model: [do_common_thing, do_regular_thing, do_visitor_thing]

visitor_spec: &visitor_spec
  spec_model: [do_common_thing, do_visitor_thing]

admin:
  <<: *common
  <<: *signed_user
  <<: *admin_spec

regular:
  <<: *common
  <<: *signed_user
  <<: *regular_spec

visitor:
  <<: *common
  <<: *visitor_spec