development:
  sessions:
    default:
      database: app_development
      hosts:
        - localhost:27017
      options:
  options:

staging:
  sessions:
    default:
      database: app_staging
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: app_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
