development:
  sessions:
    default:
      database: newintown_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false