development:
  whitelabel:
    key: a
    token: a
  secret_key_base: a
  stripe_api_key: a

test:
  open_exchange_rates:
    app_id: some_key
  whitelabel:
    key: a
    token: a
  secret_key_base: a
  stripe_api_key: a

staging:
  secret_key_base: whatever
  stripe_api_key: a

production:
  secret_key_base: whatever
  stripe_api_key: whatever
